# So parent files don't get applied
root: true

env:
  es6: true
  browser: true
  node: true

extends: eslint:recommended

rules:
  # Errors
  array-bracket-spacing: [2, never]
  arrow-spacing: 2
  arrow-parens: 2
  block-spacing: [2, always]
  brace-style: 2
  comma-dangle: [2, only-multiline]
  comma-spacing: [2, {before: false, after: true}]
  comma-style: [2, last]
  computed-property-spacing: [2, never]
  consistent-this: [2, self]
  consistent-return: 0 # Wishlist, one day
  dot-notation: 2
  dot-location: [2, property]
  eqeqeq: [2, smart]
  eol-last: 2
  indent: [2, 3, {SwitchCase: 1}]
  id-blacklist: [2, e]
  jsx-quotes: [2, prefer-double]
  keyword-spacing: 2
  key-spacing: 2
  max-len: [2, 300, 4]
  new-cap: [0, {capIsNew: true, newIsCap: true}] # Wishlist, one day
  no-unused-expressions: 2
  no-unused-vars: 2
  no-shadow: 0 # Wishlist, one day
  no-spaced-func: 2
  no-multi-spaces: 2
  no-undef: 2
  no-empty-pattern: 2
  no-dupe-keys: 2
  no-dupe-args: 2
  no-duplicate-case: 2
  no-cond-assign: 2
  no-extra-semi: 2
  no-extra-boolean-cast: 2
  no-unneeded-ternary: 2
  no-unreachable: 2
  no-var: 2
  object-curly-spacing: [0, never]
  one-var: [2, never]
  padded-blocks: [0, never]
  prefer-arrow-callback: 0 # Wishlist, one day
  prefer-const: 2
  prefer-template: 0
  quotes: [2, single, avoid-escape]
  semi: [2, always]
  space-before-blocks: [2, always]
  space-before-function-paren: [2, never]
  space-in-parens: [error, never]
  space-infix-ops: 0
  space-unary-ops: [2, { words: true, nonwords: false }]
  yoda: 2

  # Disabled
  strict: 0
  no-case-declarations: 0

parser: babel-eslint

plugins:

ecmaFeatures:
  jsx: true
  modules: true
